const pohina = [
    { "fi": "Ketterä kehitys", "en": "Agile development" },
    { "fi": "Pivotointi", "en": "Pivoting" },
    { "fi": "Kryptovaluutta", "en": "Crypto\xADcurrency" },
    { "fi": "Skaalautuvuus", "en": "Scalability" },
    { "fi": "Synergia", "en": "Synergy" },
    { "fi": "Käyttäjä\xADlähtöinen sisältö", "en": "User-generated content" },
    { "fi": "Orgaaninen", "en": "Organic" },
    { "fi": "Joukkoistaminen", "en": "Crowdsourcing" },
    { "fi": "Optimoitu", "en": "Optimized" },
    { "fi": "Kasvuhakkerointi", "en": "Growth hacking" },
    { "fi": "Massadata", "en": "Big data" },
    { "fi": "Rautalankamalli", "en": "Wireframe" },
    { "fi": "Disruptoida", "en": "Disrupt" },
    { "fi": "Deprekoida", "en": "Deprecate" },
    { "fi": "Diversiteetti", "en": "Diversity" },
    { "fi": "Alusta", "en": "Platform" },
    { "fi": "Optionaalisuus", "en": "Optionality" },
    { "fi": "Bootstrappaus", "en": "Bootstrapping" },
    { "fi": "Ideaatio", "en": "Ideation" },
    { "fi": "Ekosysteemi", "en": "Ecosystem" },
    { "fi": "Iteraatio", "en": "Iteration" }
]

const normal = [
    { "fi": "Nauris", "en": "Turnip" },
    { "fi": "Urho Kekkonen", "en": "Urho Kekkonen" },
    { "fi": "Maatalous", "en": "Agriculture" },
    { "fi": "Hylkeenpoikanen", "en": "Seal cub" },
    { "fi": "Villapaita", "en": "Wool Jersey" },
    { "fi": "Äreä", "en": "Grumpy" },
    { "fi": "Öljyväri", "en": "Oil paint" },
    { "fi": "Rakkaus", "en": "Love" },
    { "fi": "Sirkusteltta", "en": "Circus tent" },
    { "fi": "Jäätelö", "en": "Ice cream" },
    { "fi": "Karaokeisäntä", "en": "Karaoke host" },
    { "fi": "Laiton", "en": "Illegal" },
    { "fi": "Pokémon", "en": "Pokémon" },
    { "fi": "Nakkilan kunta", "en": "Municipality of Nakkila" },
    { "fi": "Perseensuti", "en": "Asswipe" },
    { "fi": "Drinkkilista", "en": "Drink list" },
    { "fi": "Luostari", "en": "Monastery" },
    { "fi": "Aineeton", "en": "Immaterial" },
    { "fi": "Vuohi", "en": "Goat" },
]

export {pohina, normal}